export { default as Home } from "./home/home"
export { default as Login } from "./login/login"
export { default as Schedule } from "./schedule/schedule"
export { default as Grade } from "./grade/grade"
export { default as NotFound } from "./notFound/notFound"
export { default as Courses } from "./courses/courses"
export { default as CourseDetails } from "./courseDetails/courseDetails"